MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.9                       # [osx and x86_64]

boost:
  - 1.78.0
hdf5:
  - 1.14.0
python:
  - 3.9
  - 3.10
  - 3.11


pin_run_as_build:
  boost: x.x
  hdf5: x.x.x
  python: x.x

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
c_compiler_version:            # [unix]
  - 12                         # [linux]
  - 16                         # [osx]

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]

c_stdlib_version:              # [unix]
  - 2.12                       # [linux64]
  - 10.9                       # [osx and x86_64]
  - 11.0                       # [osx and arm64]

cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
cxx_compiler_version:          # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
llvm_openmp:                   # [osx]
  - 16                         # [osx]
